name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build -- --prod --base-href='/project-242-fe/'
        env:
          GOOGLEMAPS__API_KEY: ${{ secrets.GOOGLEMAPS__API_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GOOGLEMAPS__API_KEY: ${{ secrets.GOOGLEMAPS__API_KEY }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist/fe
