name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GOOGLEMAPS__API_KEY: ${{ secrets.GOOGLEMAPS__API_KEY }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist/fe
          BUILD_SCRIPT: npm install && npm run build -- --prod --base-href='/project-242-fe/'
